# 从各节点文件导入映射
from .ollama_node import (
    NODE_CLASS_MAPPINGS as OLLAMA_NODE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as OLLAMA_DISPLAY_NAMES
)

from .string_utils import (
    NODE_CLASS_MAPPINGS as STRING_UTILS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STRING_UTILS_DISPLAY_NAMES
)

# 合并所有映射
NODE_CLASS_MAPPINGS = {
    **OLLAMA_NODE_MAPPINGS,
    **STRING_UTILS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **OLLAMA_DISPLAY_NAMES,
    **STRING_UTILS_DISPLAY_NAMES
}

# 定义公开接口
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]